// AUTO-GENERATED by build step. Do not edit manually.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import type React from 'react'

export const componentRegistry: Record<string, () => Promise<{ default: React.ComponentType<Record<string, unknown>> }>> = {
  Button: () => import('../../src/components/Button').then(m => ({ default: m.Button as React.ComponentType<Record<string, unknown>> })),
}
